[package]
name = "machine-translation"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.90"
rust-bert = "0.19.0"
tch = "0.8.0"
indicatif = "0.16.2"
console = { version = "0.16", features = ["ansi-parsing"] }
